#Generated by bitnik_apm_generator
class CreateApmTestInfraestructure < ActiveRecord::Migration
  def self.up
    create_table "bitnik_apm_foo_objects" do |t|
      t.column :key, :string
      t.column :name, :string
    end
    create_table "bitnik_apm_foo_consumers" do |t|
      t.column :name, :string
    end
  end

  def self.down
    drop_table "bitnik_apm_foo_objects"
    drop_table "bitnik_apm_foo_consumers"
  end
end
