#Generated by bitnik_apm_generator
class CreateAttentionConcepts < ActiveRecord::Migration
  def self.up
    create_table "attention_destinies" do |t|
      t.column :key, :string
      t.column :is_explicit, :boolean
      t.column :is_implicit, :boolean
      t.column :from, :string
      t.column :attention_generator_id, :integer
      t.column :attention_generator_type, :string
      t.timestamps
    end

    create_table "attention_points" do |t|
      t.column :value, :integer
      t.column :mode, :string
      t.column :attention_destiny_id, :integer
      t.column :attention_profile_id, :integer
      t.timestamps
    end

    create_table "attention_reference_points" do |t|
      t.column :value, :integer
      t.column :mode, :string
      t.column :attention_destiny_reference_id, :integer
      t.column :attention_profile_id, :integer
      t.timestamps
    end

    create_table "attention_profiles" do |t|
      t.column :attention_source_id, :integer
      t.column :attention_source_type, :string
      t.column :name, :string
      t.timestamps
    end

    create_table "attention_destiny_references" do |t|
      t.column :key, :string
      t.column :name, :string
      t.column :mime_type, :string
      t.column :from, :string
      t.column :author_key, :string
      t.column :author_value, :string
      t.column :author_from, :string
      t.column :author_updated_at, :datetime
      t.column :is_explicit, :boolean
      t.column :is_implicit, :boolean
      t.column :from, :string
      t.timestamps
    end
  end

  def self.down
    drop_table "attention_points"
    drop_table "attention_reference_points"
    drop_table "attention_profiles"
    drop_table "attention_destinies"
    drop_table "attention_destiny_references"
  end
end
